### ISSUE TITLE
Weapon Switching: Scenes And States

### ISSUE THREAD

**Issue by WoahWare** [Gab-ani/Godot-3D-Mechanics-Museum#2]
First, just want to say that what you have created is awesome!  Fantastic job on this type of framework!

I am not sure if you will cover this topic in the current series you have on youtube (which is also well done btw), but I wanted to ask anyway. Also, this maybe just me not understanding something (I am about a month into Godot, so I am definitely new haha), but...

I have been thinking about if the character has a different set of possible weapons, each with their own states (ie: 2 handed weapon (like a big sword or big mace), bow, magic wand, etc. all are going to have say a different idle stance, a different attack, and different combo states). Here's my question -- do you have thoughts as to how that should be organized?

What I mean is, creating the new states should not be that big of an issue, but where it does become a problem (that I cannot seem to wrap my head around) is for when we decide for the character to switch weapons. Currently, we have a sword which is attached to a bone attachment on a wrist and that is currently defined as a scene. But, for other weapon types, which also might need to use that same bone attachment, do we also create separate (not part of the player node) scenes for those weapons as well, but then have code to add or remove those scenes as children to that bone attachment as needed?   Is there a better way of doing this?

Huge thank you for any insight you can provide. 
Again, great work on everything. Keep it up!  👍

**Comment by Gab-ani** [comment]
First, the before created resources: you can rewatch closely combat design chapters in 3rd episode, I talk there about mapping our moves by the weapon, and I also have a joke "commented section" of several weapons in the model for future. I also answered some comment threads under all controller vids, there were topics like weapon/stances switching, sheathing etc discussed, you can probably find something interesting hunting those comments.

Secondly, how I am designing: think in states (Moves). As my states currently have an animation per state, us wanting to have weapon switching, the weapon switching itself is probably an animation, if we are existing in 3D and post 1998, amirite? If so, instant insight: cycle weapons is a default action of high priority (higher than any attack, but lower than rolls/evades I'd say). Either SwitchWeapons is a single new Move, the animation is our player putting the weapon to it's sheathed nest, then unsheathes the next. Or we break it down to Sheath and Unsheathe, (which is probably cleaner). Then we just hide one weapon and show another in the middle of SwitchWeapons or on_exit of sheath and on_enter of unsheath.
Bonus point if your weapons have different sitting-on-a-body places and aren't hidden, just literally put on the back, for example. In this case you'll need to implement another logic layer which manages all that, then create a bunch of sitting places on your body, ie, back for bows, thighs for swords, daggers etc. Then your states reparent your weapons instead of hiding. Have different sheathe animations, feel free to change them on the fly with the inventory logic layer (I have more on that issue in the last chapter of 4th controller video about reactions).

And lastly I'd probably do some work with weapons, for example, I'd add a flag into a weapon to signal if it's sheathed. The reason is better visuals usage later. Currently my visuals are flat, but that's only because the whole thing is a prototype, in a game visuals have a ton of code too. For example, our weapon skin can emit particles and FX, we surely want to stop them in sheathed state. How to do it? State flips the flag in the weapon, but it's usage is outside of the model, it's purely for visuals to change some FX or models. For example, most games change swords models into a handle with no blade when sheathed, for the blade not to clip/simmer during parkours etc.

**Comment by Gab-ani** [comment]
I'm leaving for two weeks tomorrow and won't be able to comment further, I'd close the issue rn. If you have more questions, feel free to ask them in youtube comments or by email. At least, youtube shows me notifications, but an issue in the repo I found only due the email from github, in other case I'd randomly found out it in like 4 weeks :D.
Hope I helped ^__^.
